name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gitbeaver/release:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: gitbeaver
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker image to docker.io
      run: docker push gitbeaver/release:latest
    - name: Push docker image to gcr
      uses: mattes/gce-docker-push-action@v1
      with:
        creds: ${{ secrets.GOOGLE_DOCKER_REPO_SA_KEY }}
        src: gitbeaver/release:latest
        dst: eu.gcr.io/breuni-infra-gitbeaver/release